{{- range $key, $issuer := .Values.clusterIssuers }}
{{- if $issuer.enabled }}
---
## ClusterIssuer for Let's Encrypt {{ $key }} (DNS-01 via Cloudflare)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $issuer.name }}
spec:
  acme:
    email: {{ $issuer.email }}
    server: {{ $issuer.server }}
    privateKeySecretRef:
      name: {{ $issuer.privateKeySecret }}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ $.Values.cloudflare.apiTokenSecretRef.name }}
              key: {{ $.Values.cloudflare.apiTokenSecretRef.key }}
{{- end }}
{{- end }}
