---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDCIZVkms452hbwt2Wr6CN1am7UrFcWVklPgq+nsXcvctXr02Palw+e/3rMfUFUgqk0jQaX84l8LqSaeBRgOJmxlPlFS/RzHh2g2jP57m8WBZrqFC3D7huV3JhYyB5u7X1S/kTxXY4uJzLOjIX00KQ7gv5Fx/OzSC4yenRvxQkLTXJMC0QIdgX0ZLXZ/+2vS6mL2QXSFq3qkus3GsxQxHqRrxV7uZ6+uxorVBv8Qp6QD7MGVc+SeIcBw98Lqyg+byt9+zIcnID1ii113EnPX5LMGJkdIdjBKPE9JTjNFp9VPsmYYbjo5Q9tPm4T+1io0YV9y1+H//weU/y1ieHQHtLKqgPowakyIRJrk+TB/ejarlb1I0C75G7IFj9n0qgLgPB22B8N5hbU85tEIDejfrhTj5FFYm4mYS8EtRKZi+I/PBwYjY/533uvSfsAaGN5YHI6ixFHwkWx3tVdgFOc4OzKivx4NdiH/80kzP7glPBRVP0Wd5jKYo6DhXuz7mmYtZBTpqN6uNATUK0mYnKoy2AG03xQBfwWYzNdJcMJ7IE5yO8ujkHMzhm5T4bG2aIGDWVJ9bixPatn8N4pHDNoYeEiyfAYuv5c0gmM32vmXudrBRrj8ncqOAENakde7BpumEmMuj84XCDgBCatGyD6Kj8PWzE345R8XjAyTzQpwSCc6IzxzVqVt83fkkJIoJji6NQAcPIsyErbXrMawLLk/oNlz4UsvLgjd10rQ8bIIQ9Oj/PQbVIQGRZJj0/yjB4paC/DUYI4HA==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
