apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: traefik-reverse-proxy
    meta.helm.sh/release-namespace: traefik-reverse-proxy
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer   # pick AZ after node is chosen
allowVolumeExpansion: true
parameters:
  type: gp3
  csi.storage.k8s.io/fstype: ext4