{{- $cert := genSelfSignedCert .Values.ingressRoute.host nil (list .Values.ingressRoute.host) (int .Values.tls.durationDays) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingressRoute.edgeTlsSecretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commit-api.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
