{{- $serviceName := include "commit-api.fullname" . -}}
{{- $namespace := .Values.namespace -}}
{{- $dnsNames := list $serviceName (printf "%s.%s" $serviceName $namespace) (printf "%s.%s.svc" $serviceName $namespace) (printf "%s.%s.svc.cluster.local" $serviceName $namespace) -}}
{{- $cert := genSelfSignedCert (printf "%s.%s.svc.cluster.local" $serviceName $namespace) nil $dnsNames (int .Values.tls.durationDays) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.appSecretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commit-api.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
