apiVersion: v1
kind: Service
metadata:
  name: {{ include "commit-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "commit-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "commit-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
