## helm-charts/env-dev/cert-manager/values.yaml

cloudflare:
  # This Secret must exist in the cert-manager namespace for ClusterIssuers.
  apiTokenSecretRef:
    name: cloudflare-api-token-secret
    key: api-token

clusterIssuers:
  staging:
    enabled: true
    name: letsencrypt-staging-cloudflare
    email: devops.admin@cloudsmesh.be
    ### first TEST on STAGING Let's Encrypt - Certificate Authority: ###
    # This is a staging server (does not issue valid certificates, but allows testing without limits).
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecret: letsencrypt-staging-cloudflare-account-key

  production:
    enabled: true
    name: letsencrypt-prod-cloudflare
    email: devops.admin@cloudsmesh.be
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecret: letsencrypt-prod-cloudflare-account-key

certificates:
  devWildcardStaging:
    enabled: true
    name: dev-cloudsmesh-be-staging-tls
    namespace: traefik-reverse-proxy
    secretName: dev-cloudsmesh-be-staging-tls
    issuerRefName: letsencrypt-staging-cloudflare
    dnsNames:
      - "*.dev.cloudsmesh.be"
      - "dev.cloudsmesh.be"

  # Wildcard Certificate configuration (*.dev.cloudsmesh.be)
  devWildcardProduction:
    enabled: true
    name: dev-cloudsmesh-be-prod-tls
    namespace: traefik-reverse-proxy
    secretName: dev-cloudsmesh-be-prod-tls
    issuerRefName: letsencrypt-prod-cloudflare
    dnsNames:
      - "*.dev.cloudsmesh.be"
      - "dev.cloudsmesh.be"
